# Generated by Django 3.2.6 on 2021-09-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=50)),
                ('tags', models.TextField(max_length=120)),
                ('discription', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10000)),
                ('img', models.ImageField(null=True, upload_to='image/')),
            ],
        ),
    ]
